local LSM = LibStub("LibSharedMedia-3.0")

LSM:Register("background", "Birg00", [[Interface\Addons\jynxiUI\media\background\Birg00.tga]]) 
LSM:Register("background", "HalBackground", [[Interface\Addons\jynxiUI\media\background\HalBackground.tga]])
LSM:Register("background", "HalBackgroundA", [[Interface\Addons\jynxiUI\media\background\HalBackgroundA.tga]])
LSM:Register("background", "LynShadow", [[Interface\Addons\jynxiUI\media\background\LynShadow.tga]])
LSM:Register("background", "Roth1", [[Interface\Addons\jynxiUI\media\background\Roth1.tga]])

LSM:Register("border", "AzeriteBorder", [[Interface\Addons\jynxiUI\media\border\AzeriteBorder.tga]])
LSM:Register("border", "AzeriteBorder Tooltip", [[Interface\Addons\jynxiUI\media\border\AzeriteBorder_Tooltip.tga]])
LSM:Register("border", "CaithBorder", [[Interface\Addons\jynxiUI\media\border\CaithBorder.tga]])
LSM:Register("border", "CaithBorder2", [[Interface\Addons\jynxiUI\media\border\CaithBorder2.tga]])
LSM:Register("border", "CaithBorder3", [[Interface\Addons\jynxiUI\media\border\CaithBorder3.tga]])
LSM:Register("border", "CircleBorder", [[Interface\Addons\jynxiUI\media\border\circle1.tga]])
LSM:Register("border", "GW2Border", [[Interface\Addons\jynxiUI\media\border\Gw2bord.tga]])
LSM:Register("border", "HalBorder", [[Interface\Addons\jynxiUI\media\border\HalBorder.tga]])
LSM:Register("border", "IshBorder", [[Interface\Addons\jynxiUI\media\border\IshBorder.tga]])
LSM:Register("border", "KkthnxBorder", [[Interface\Addons\jynxiUI\media\border\Kkthnx_Border.tga]])
LSM:Register("border", "kwiBorder", [[Interface\Addons\jynxiUI\media\border\kwiBorder.tga]])
LSM:Register("border", "Lightspark1", [[Interface\Addons\jynxiUI\media\border\Lightspark1.tga]])
LSM:Register("border", "Lightspark2", [[Interface\Addons\jynxiUI\media\border\Lightspark2.tga]])
LSM:Register("border", "Lightspark3", [[Interface\Addons\jynxiUI\media\border\Lightspark3.tga]])
LSM:Register("border", "Lightspark4", [[Interface\Addons\jynxiUI\media\border\Lightspark4.tga]])
LSM:Register("border", "LynShadow", [[Interface\Addons\jynxiUI\media\border\LynShadow.tga]])
LSM:Register("border", "MawBorder", [[Interface\Addons\jynxiUI\media\border\MawBorder.tga]])
LSM:Register("border", "MikkBorder", [[Interface\Addons\jynxiUI\media\border\Mikk.tga]])
LSM:Register("border", "MikkBorder2", [[Interface\Addons\jynxiUI\media\border\Mikk2.tga]])
LSM:Register("border", "Roth", [[Interface\Addons\jynxiUI\media\border\roth.tga]])
LSM:Register("border", "Roth1", [[Interface\Addons\jynxiUI\media\border\roth1.tga]])
LSM:Register("border", "Roth2", [[Interface\Addons\jynxiUI\media\border\roth2.tga]])
LSM:Register("border", "Thin", [[Interface\Addons\jynxiUI\media\border\Thin.tga]])

LSM:Register("font", "Bebas Neue", [[Interface\Addons\jynxiUI\media\fonts\BebasNeue-Regular.ttf]])
LSM:Register("font", "Expressway", [[Interface\Addons\jynxiUI\media\fonts\expressway.ttf]])
LSM:Register("font", "Gotham N-Black", [[Interface\Addons\jynxiUI\media\fonts\Gotham-Narrow-Black.ttf]])
LSM:Register("font", "Gotham N-Bold", [[Interface\Addons\jynxiUI\media\fonts\Gotham-Narrow-Bold.ttf]])
LSM:Register("font", "Gotham XN-Black", [[Interface\Addons\jynxiUI\media\fonts\GothamXNarrow-Black.ttf]])
LSM:Register("font", "Gotham XN-Ultra", [[Interface\Addons\jynxiUI\media\fonts\GothamXNarrow-Ultra.ttf]])
LSM:Register("font", "Gotham XN-Ultra CAPS", [[Interface\Addons\jynxiUI\media\fonts\GothamXNarrowUltraCAPS.ttf]])
LSM:Register("font", "LEMON MILK", [[Interface\Addons\jynxiUI\media\fonts\LEMONMILK-Medium.ttf]])
LSM:Register("font", "Open Sans SemiCondensed Bold", [[Interface\Addons\jynxiUI\media\fonts\OpenSans_SemiCondensed-Bold.ttf]]) 
LSM:Register("font", "Open Sans Bold", [[Interface\Addons\jynxiUI\media\fonts\OpenSans-Bold.ttf]])
LSM:Register("font", "Roboto Slab", [[Interface\Addons\jynxiUI\media\fonts\RobotoSlab.ttf]])


LSM:Register("statusbar", "Cabaret 1", [[Interface\Addons\jynxiUI\media\statusbar\cabaret1.tga]])  
LSM:Register("statusbar", "Cabaret 2", [[Interface\Addons\jynxiUI\media\statusbar\cabaret2.tga]])  
LSM:Register("statusbar", "Cabaret 3", [[Interface\Addons\jynxiUI\media\statusbar\cabaret3.tga]])  
LSM:Register("statusbar", "Cabaret 4", [[Interface\Addons\jynxiUI\media\statusbar\cabaret4.tga]])  
LSM:Register("statusbar", "Cabaret 5", [[Interface\Addons\jynxiUI\media\statusbar\cabaret5.tga]])  
LSM:Register("statusbar", "Dragonflight", [[Interface\Addons\jynxiUI\media\statusbar\DFHealth.tga]])  
LSM:Register("statusbar", "ElvUI A", [[Interface\Addons\jynxiUI\media\statusbar\ElvUI A.tga]])  
LSM:Register("statusbar", "ElvUI B", [[Interface\Addons\jynxiUI\media\statusbar\ElvUI B.tga]])    
LSM:Register("statusbar", "ElvUI C", [[Interface\Addons\jynxiUI\media\statusbar\ElvUI C.tga]])    
LSM:Register("statusbar", "ElvUI D", [[Interface\Addons\jynxiUI\media\statusbar\ElvUI D.tga]])    
LSM:Register("statusbar", "ElvUI E", [[Interface\Addons\jynxiUI\media\statusbar\ElvUI E.tga]])    
LSM:Register("statusbar", "ElvUI F", [[Interface\Addons\jynxiUI\media\statusbar\ElvUI F.tga]])    
LSM:Register("statusbar", "ElvUI G", [[Interface\Addons\jynxiUI\media\statusbar\ElvUI G.tga]])    
LSM:Register("statusbar", "ElvUI H", [[Interface\Addons\jynxiUI\media\statusbar\ElvUI H.tga]])    
LSM:Register("statusbar", "ElvUI I", [[Interface\Addons\jynxiUI\media\statusbar\ElvUI I.tga]])    
LSM:Register("statusbar", "ElvUI J", [[Interface\Addons\jynxiUI\media\statusbar\ElvUI J.tga]])    
LSM:Register("statusbar", "ElvUI K", [[Interface\Addons\jynxiUI\media\statusbar\ElvUI K.tga]])    
LSM:Register("statusbar", "ElvUI L", [[Interface\Addons\jynxiUI\media\statusbar\ElvUI L.tga]])    
LSM:Register("statusbar", "ElvUI M", [[Interface\Addons\jynxiUI\media\statusbar\ElvUI M.tga]])    
LSM:Register("statusbar", "ElvUI N", [[Interface\Addons\jynxiUI\media\statusbar\ElvUI N.tga]])    
LSM:Register("statusbar", "ElvUI O", [[Interface\Addons\jynxiUI\media\statusbar\ElvUI O.tga]])    
LSM:Register("statusbar", "ElvUI P", [[Interface\Addons\jynxiUI\media\statusbar\ElvUI P.tga]])    
LSM:Register("statusbar", "ElvUI Q", [[Interface\Addons\jynxiUI\media\statusbar\ElvUI Q.tga]])      
LSM:Register("statusbar", "ElvUI R", [[Interface\Addons\jynxiUI\media\statusbar\ElvUI R.tga]])      
LSM:Register("statusbar", "Fer4", [[Interface\Addons\jynxiUI\media\statusbar\fer4.tga]])      
LSM:Register("statusbar", "Fer8", [[Interface\Addons\jynxiUI\media\statusbar\fer8.tga]])     
LSM:Register("statusbar", "G1", [[Interface\Addons\jynxiUI\media\statusbar\G1.tga]]) 
LSM:Register("statusbar", "G2", [[Interface\Addons\jynxiUI\media\statusbar\G2.tga]]) 
LSM:Register("statusbar", "G3", [[Interface\Addons\jynxiUI\media\statusbar\G3.tga]]) 
LSM:Register("statusbar", "G4", [[Interface\Addons\jynxiUI\media\statusbar\G4.tga]]) 
LSM:Register("statusbar", "GW", [[Interface\Addons\jynxiUI\media\statusbar\GW.tga]])  
LSM:Register("statusbar", "Glaze", [[Interface\Addons\jynxiUI\media\statusbar\Glaze.tga]])      
LSM:Register("statusbar", "Glaze2", [[Interface\Addons\jynxiUI\media\statusbar\Glaze2.tga]])      
LSM:Register("statusbar", "GoldpawA", [[Interface\Addons\jynxiUI\media\statusbar\GoldpawA.tga]])      
LSM:Register("statusbar", "GoldpawB", [[Interface\Addons\jynxiUI\media\statusbar\GoldpawB.tga]])     
LSM:Register("statusbar", "GW", [[Interface\Addons\jynxiUI\media\statusbar\gw.tga]])      
LSM:Register("statusbar", "GW2", [[Interface\Addons\jynxiUI\media\statusbar\gw2.tga]])      
LSM:Register("statusbar", "HalA", [[Interface\Addons\jynxiUI\media\statusbar\HalA.tga]])      
LSM:Register("statusbar", "HalB", [[Interface\Addons\jynxiUI\media\statusbar\HalB.tga]])      
LSM:Register("statusbar", "HalC", [[Interface\Addons\jynxiUI\media\statusbar\HalC.tga]])      
LSM:Register("statusbar", "HalD", [[Interface\Addons\jynxiUI\media\statusbar\HalD.tga]])      
LSM:Register("statusbar", "HalE", [[Interface\Addons\jynxiUI\media\statusbar\HalE.tga]])      
LSM:Register("statusbar", "HalF", [[Interface\Addons\jynxiUI\media\statusbar\HalF.tga]])      
LSM:Register("statusbar", "HalG", [[Interface\Addons\jynxiUI\media\statusbar\HalG.tga]])      
LSM:Register("statusbar", "HalH", [[Interface\Addons\jynxiUI\media\statusbar\HalH.tga]])      
LSM:Register("statusbar", "HalI", [[Interface\Addons\jynxiUI\media\statusbar\HalI.tga]])      
LSM:Register("statusbar", "HalJ", [[Interface\Addons\jynxiUI\media\statusbar\HalJ.tga]])      
LSM:Register("statusbar", "HalK", [[Interface\Addons\jynxiUI\media\statusbar\HalK.tga]])      
LSM:Register("statusbar", "HalL", [[Interface\Addons\jynxiUI\media\statusbar\HalL.tga]])      
LSM:Register("statusbar", "HalM", [[Interface\Addons\jynxiUI\media\statusbar\HalM.tga]])      
LSM:Register("statusbar", "HalN", [[Interface\Addons\jynxiUI\media\statusbar\HalN.tga]])      
LSM:Register("statusbar", "HalO", [[Interface\Addons\jynxiUI\media\statusbar\HalO.tga]])      
LSM:Register("statusbar", "HalP", [[Interface\Addons\jynxiUI\media\statusbar\HalP.tga]])      
LSM:Register("statusbar", "HalQ", [[Interface\Addons\jynxiUI\media\statusbar\HalQ.tga]])      
LSM:Register("statusbar", "HalR", [[Interface\Addons\jynxiUI\media\statusbar\HalR.tga]])      
LSM:Register("statusbar", "HalS", [[Interface\Addons\jynxiUI\media\statusbar\HalS.tga]])      
LSM:Register("statusbar", "HalT", [[Interface\Addons\jynxiUI\media\statusbar\HalT.tga]])      
LSM:Register("statusbar", "HalU", [[Interface\Addons\jynxiUI\media\statusbar\HalU.tga]])      
LSM:Register("statusbar", "HalV", [[Interface\Addons\jynxiUI\media\statusbar\HalV.tga]])      
LSM:Register("statusbar", "HalW", [[Interface\Addons\jynxiUI\media\statusbar\HalW.tga]])      
LSM:Register("statusbar", "HalX", [[Interface\Addons\jynxiUI\media\statusbar\HalX.tga]])      
LSM:Register("statusbar", "Led01", [[Interface\Addons\jynxiUI\media\statusbar\Led01.tga]])      
LSM:Register("statusbar", "Led02", [[Interface\Addons\jynxiUI\media\statusbar\Led02.tga]])      
LSM:Register("statusbar", "Led03", [[Interface\Addons\jynxiUI\media\statusbar\Led03.tga]])      
LSM:Register("statusbar", "Roth1", [[Interface\Addons\jynxiUI\media\statusbar\Roth1.tga]])      
LSM:Register("statusbar", "Ruben", [[Interface\Addons\jynxiUI\media\statusbar\Ruben.tga]])      
LSM:Register("statusbar", "Skullflower", [[Interface\Addons\jynxiUI\media\statusbar\Skullflower.tga]])      
LSM:Register("statusbar", "Skullflower 1", [[Interface\Addons\jynxiUI\media\statusbar\Skullflower1.tga]])      
LSM:Register("statusbar", "Skullflower 2", [[Interface\Addons\jynxiUI\media\statusbar\Skullflower2.tga]])      
LSM:Register("statusbar", "Skullflower 3", [[Interface\Addons\jynxiUI\media\statusbar\Skullflower3.tga]])      
LSM:Register("statusbar", "Skullflower 4", [[Interface\Addons\jynxiUI\media\statusbar\Skullflower4.tga]])      
LSM:Register("statusbar", "Skullflower 5", [[Interface\Addons\jynxiUI\media\statusbar\Skullflower5.tga]])      
LSM:Register("statusbar", "Skullflower Gradient", [[Interface\Addons\jynxiUI\media\statusbar\SkullflowerGradient.tga]])      
LSM:Register("statusbar", "Skullflower Gradient 1", [[Interface\Addons\jynxiUI\media\statusbar\SkullflowerGradient1.tga]])      
LSM:Register("statusbar", "Skullflower Light", [[Interface\Addons\jynxiUI\media\statusbar\SkullflowerLight.tga]])      
LSM:Register("statusbar", "Skullflower Neon", [[Interface\Addons\jynxiUI\media\statusbar\SkullflowerNeon.tga]])      
LSM:Register("statusbar", "Tapestry 1", [[Interface\Addons\jynxiUI\media\statusbar\tap1.tga]])  
LSM:Register("statusbar", "Tapestry 2", [[Interface\Addons\jynxiUI\media\statusbar\tap2.tga]])  
LSM:Register("statusbar", "Tapestry 3", [[Interface\Addons\jynxiUI\media\statusbar\tap3.tga]])  
LSM:Register("statusbar", "Tapestry 4", [[Interface\Addons\jynxiUI\media\statusbar\tap4.tga]])  
LSM:Register("statusbar", "wGlass", [[Interface\Addons\jynxiUI\media\statusbar\Wglass.tga]])  